sudo: true
dist: trusty

env:
  global:
    - CC_TEST_REPORTER_ID=${CC_REPORTER_ID}

services:
  - docker

before_install:
  - docker build --no-cache -t ${TRAVIS_REPO_SLUG} .
  - docker images
  - bash travis/docker_run.sh
  - bash travis/code_climate.sh

install:
  - docker exec registry-cli composer install
  - docker exec registry-cli install-php-extensions xdebug

before_script:
  - docker exec registry-cli cc-test-reporter before-build
  - docker pull alpine && docker tag alpine localhost:5000/alpine:test && docker push localhost:5000/alpine:test

script:
  - docker exec registry-cli composer code-style
  - docker exec registry-cli composer test:with-coverage
  - docker exec registry-cli composer test:functional

after_script:
  - docker exec registry-cli cc-test-reporter after-build -t clover

deploy:
  skip_cleanup: true
  provider: script
  script: bash travis/deploy_master.sh
  on:
    branch: master
