sudo: true
dist: trusty

env:
  global:
    - CC_TEST_REPORTER_ID=${CC_REPORTER_ID}

services:
  - docker

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - docker build --no-cache -t ${TRAVIS_REPO_SLUG} .
  - docker images
  - bash travis/docker_run.sh

install:
  - docker exec registry-cli composer install
  - docker exec registry-cli install-php-extensions xdebug

before_script:
  - ./cc-test-reporter before-build
  - docker pull alpine && docker tag alpine localhost:5000/alpine:test && docker push localhost:5000/alpine:test

script:
  - docker exec registry-cli composer code-style
  - docker exec registry-cli composer test:with-coverage
  - docker exec registry-cli composer test:functional
  - docker cp registry-cli:/usr/lib/registry/clover.xml .
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT; fi

after_script:
  - ./cc-test-reporter after-build --exit-code ${TRAVIS_TEST_RESULT}

deploy:
  skip_cleanup: true
  provider: script
  script: bash travis/deploy_master.sh
  on:
    branch: master
