version: "3.8"

volumes:
  vendor-data:

services:
  registry:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./composer.json:/usr/lib/registry/composer.json:delegated
      - ./composer.lock:/usr/lib/registry/composer.lock:delegated
      - ./src:/usr/lib/registry/src:delegated
      - ./bin:/usr/lib/registry/bin:delegated
      - ./tests:/usr/lib/registry/tests:delegated
      - vendor-data:/usr/lib/registry/vendor
