version: "3.8"

volumes:
  vendor-data:

networks:
  registry:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]
    networks:
      - registry
    volumes:
      - ./composer.json:/usr/lib/registry/composer.json:delegated
      - ./composer.lock:/usr/lib/registry/composer.lock:delegated
      - ./src:/usr/lib/registry/src:delegated
      - ./bin:/usr/lib/registry/bin:delegated
      - ./tests:/usr/lib/registry/tests:delegated
      - vendor-data:/usr/lib/registry/vendor

  registry:
    image: registry:2
    ports:
      - 5000:5000
    networks:
      - registry
    volumes:
    - ./docker/registry/config.yml:/etc/docker/registry/config.yml
