version: "3.8"

volumes:
  vendor-data:

networks:
  registry:

services:
  cli:
    build:
      context: ../
      dockerfile: ./docker/dev.Dockerfile
    environment:
      XDEBUG_MODE: debug
    networks:
      - registry
    volumes:
      - ../composer.json:/usr/lib/registry/composer.json:delegated
      - ../composer.lock:/usr/lib/registry/composer.lock:delegated
      - ../phpunit.xml.dist:/usr/lib/registry/phpunit.xml:delegated
      - ../phpcs.xml.dist:/usr/lib/registry/phpcs.xml:delegated
      - ../src:/usr/lib/registry/src:delegated
      - ../bin:/usr/lib/registry/bin:delegated
      - ../tests:/usr/lib/registry/tests:delegated
      - vendor-data:/usr/lib/registry/vendor

  registry:
    image: registry:2
    ports:
      - 5000:5000
    networks:
      - registry
    volumes:
      - ../docker/registry/config.yml:/etc/docker/registry/config.yml
